### ISSUE TITLE
[Feature request] What about useContext support?

### ISSUE THREAD

**Issue by gormonn** [phryneas/use-local-slice#19]
This is a great hook!
But what if you need to put it into context?

The problem is that I don't understand how to describe the types of actions outside the hook.

Alternatively now, I am using useReducer + createSlice. However, this is a bit inconvenient because does not allow to pass action through context without dancing.

**Comment by phryneas** [comment]
You should definitely not put it into context. This library is meant for local component state only.

Context is technically not suited to be a value propagation mechanism - it is just a dependency injection mechanism, meaning you can put stuff through that changes **very rarely** or not at all, or is only consumed by a tiny part of your application.

Links for related reading:  
https://dev.to/javmurillo/react-context-all-in-one-54ck  
https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#context-and-rendering-behavior  
https://blog.isquaredsoftware.com/2021/01/context-redux-differences/

Dynamic values that change a lot should not go into Context. At that point, please use a global state management tool instead. 
Coincidentally, using modern Redux looks exactly like this library - after all, this library was inspired by modern Redux and pretty much copied the mechanisms of that. So switching from this to Redux will be a piece of cake.

If you already know Redux and want to know what "modern Redux" looks like, take a look here:
https://redux.js.org/tutorials/fundamentals/part-8-modern-redux

If you don't know Redux yet, get started here:
https://redux.js.org/tutorials/essentials/part-1-overview-concepts

**Comment by gormonn** [comment]
I was walking along the following mental path:
1. I use my reducer to manage sort / offset / filter / columnSize / columnOrdering values for useQuery on many different tables
2. Table elements are rather heavily nested and they need these values.
3. There can be many tables on one screen, with their sort / offset / filter / columnSize / columnOrdering values

Thus, I'm not sure how this can be implemented using redux, so I chose the context. Since sort / offset / filter / columnSize / columnOrdering states are encapsulated in the context of a particular table

**Comment by gormonn** [comment]
I got an explanation from https://blog.isquaredsoftware.com/2021/01/context-redux-differences/ :
>Context + useReducer relies on passing the current state value via Context. React-Redux passes the current Redux store instance via Context.
That means that when useReducer produces a new state value, all components that are subscribed to that context will be forced to re-render, even if they only care about part of the data. This may lead to performances issues, depending on the size of the state value, how many components are subscribed to that data, and how often they re-render. With React-Redux, components can subscribe to specific pieces of the store state, and only re-render when those values change.

And this is a really important detail. Even though many of the values are consumed by useQuery - which will cause redrawing anyway. However, many are not all.

And also the impossibility of using effects.

So... I think I need to look for a similar solution:
> Thus, I'm not sure how this can be implemented using redux, so I chose the context. Since sort / offset / filter / columnSize / columnOrdering states are encapsulated in the context of a particular table

https://github.com/reduxjs/redux-toolkit/issues/715
