### ISSUE TITLE
Update immer dependency to v3

### ISSUE THREAD

**Issue by Czahoo** [phryneas/use-local-slice#3]
Hey,

your hook looks really promising and I'm a big fan of the idea of combining createSlice like syntax with useReducer, but could you please update your immer dependency to the newest version?

Being honest that's the only thing which stops me from using this library and I don't want to copy-paste it cause you did amazing job creating it.

From what I saw there should be no drawbacks from using newest version of immer.

**Comment by phryneas** [comment]
Hi there, I do remember that there was a reason that I was using v1 and not v2. I think it was something about immer handling async values differently in v2. 

I'll go and take a second look at this.

**Comment by Czahoo** [comment]
Thanks for such a fast response!

Let's hope that with v3 it can work seamlessly :)

**Comment by Czahoo** [comment]
@phryneas Any progress?

**Comment by phryneas** [comment]
Sorry, didn't get around to that. Probably tomorrow in the evening. But I don't think it will be a problem, I might just have misread the documentation in the first place.

**Comment by Czahoo** [comment]
Ok, nice. Looking forward to it.

**Comment by phryneas** [comment]
I believe updating to v3 won't hurt. I published a new version 1.1.0 that depends on immer v3.

**Comment by Czahoo** [comment]
Glad to hear it!
