### ISSUE TITLE
Extracting dispatch type in Typescript

### ISSUE THREAD

**Issue by Czahoo** [phryneas/use-local-slice#5]
Hey,

I'm wondering if you have any trick to extract dispatch computed type in order to use it as dispatch object type in child components.

Currently I'm doing it manually like this:
```typescript
// Parent.tsx
import { PayloadActionReducer, ReducerMap, RedurcerWithoutPayload, useLocalSlice } from 'use-local-slice';

const initialState = {
    tab: 'default',
};

const reducers = {
    changeTab(state: typeof initialState, { payload }: { payload: string }) {
        state.tab = payload;
    }
};

// Need to redeclare cause it is not exported
type PayloadActionDispatch<P = void> = void extends P ? () => void : (payload: P) => void;
// Need to redeclare cause it is not exported
type DispatcherMap<Reducers extends ReducerMap<any>> = {
    [T in keyof Reducers]: Reducers[T] extends RedurcerWithoutPayload<any> ? PayloadActionDispatch<void> : Reducers[T] extends PayloadActionReducer<any, infer P> ? PayloadActionDispatch<P> : never;
};

export type ParentDispatcherMap = DispatcherMap<typeof reducers>;

function Parent() {
   const [state, dispatch] = useLocalSlice({
        reducers,
        initialState,
    });

   return <Child dispatch={dispatch}/>
}
```

```typescript
// Child.tsx

interface ChildProps {
    dispatch: ParentDispatcherMap ,
}

const Child: React.FC<ChildProps> = ({ dispatch }) => {
   dispatch.changeTab('other');
};
```

Obviously this way is far from perfect and exporting `DispatcherMap` type would make it less complicated, but maybe there is a trick that would make it even easier? I'm pretty new to Typescript so I am probably missing something obvious.

Also my approach would be really cumbersome if I would want to declare reducers inside the component cause then I would need to manually write reducers interface in order to export it.

**Comment by phryneas** [comment]
Good point. I published a new version that exports those types.

I think you got the best solution with `export type ParentDispatcherMap = DispatcherMap<typeof reducers>;`.

**Comment by Czahoo** [comment]
Hoped there is a better solution, but guess I will settle at this one.
